#spring:
#  data:
#    elasticsearch:
#      cluster-name: docker-cluster
#      cluster-nodes: elasticsearch:9300
#
#  elasticsearch:
#    rest:
#      uris: http://elasticsearch:9200

server:
  port: 8080


